// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtxy507GnesmRiN-NnUv1MlEdCWvJ3Yv4',
    appId: '1:852330392434:web:03b6e9699039c2f9e7cbeb',
    messagingSenderId: '852330392434',
    projectId: 'attendance-app-manual',
    authDomain: 'attendance-app-manual.firebaseapp.com',
    storageBucket: 'attendance-app-manual.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAD_KSS5aoudHl4Qonw3WnHpp5gE1Ch7g',
    appId: '1:852330392434:android:81f23202a287c29fe7cbeb',
    messagingSenderId: '852330392434',
    projectId: 'attendance-app-manual',
    storageBucket: 'attendance-app-manual.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2ncVorx9U4oALPNX459YDeWbe4pbOTCU',
    appId: '1:852330392434:ios:e377c9f1eaebf85de7cbeb',
    messagingSenderId: '852330392434',
    projectId: 'attendance-app-manual',
    storageBucket: 'attendance-app-manual.firebasestorage.app',
    iosBundleId: 'com.example.attApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2ncVorx9U4oALPNX459YDeWbe4pbOTCU',
    appId: '1:852330392434:ios:e377c9f1eaebf85de7cbeb',
    messagingSenderId: '852330392434',
    projectId: 'attendance-app-manual',
    storageBucket: 'attendance-app-manual.firebasestorage.app',
    iosBundleId: 'com.example.attApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtxy507GnesmRiN-NnUv1MlEdCWvJ3Yv4',
    appId: '1:852330392434:web:8c03943cda4a0926e7cbeb',
    messagingSenderId: '852330392434',
    projectId: 'attendance-app-manual',
    authDomain: 'attendance-app-manual.firebaseapp.com',
    storageBucket: 'attendance-app-manual.firebasestorage.app',
  );
}
